# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Edge ML'
tagline:          'Edge  Machine Learning.'
description:       Microsoft Research India
url:              'http://harsha-simhadri.org/'
baseurl:          /EdgeML

author:
  name:           'Harsha Vardhan Simhadri'
  url:            http://harsha-simhadri.org

paginate:         2

# Custom vars
github:
  repo:           https://github.com/harsha-simhadri/EdgeML

plugins:
  - jekyll-paginate
  - jekyll-gist

# For URL Setup, refer to
# https://github.com/jekyll/jekyll/issues/332#issuecomment-18952908

customurl:
  bonsai:
    pdf: /files/Bonsai.pdf
  
  protonn:
    pdf: /files/protonn.pdf
  
  rpca:
    pdf:  /files/robustpca.pdf
    code: https://github.com/andrewssobral/lrslibrary/tree/master/algorithms/mc/PG-RMC
    poster:  /files/robustpca-poster.pdf
    coltslides: /files/robustpca-colt-slides.pptx
    matlabcode: /files/Robust_PCA_code.zip
