# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Edge ML'
tagline:          'AI on the edge.'
description:      'An Intelligent Devices Expedition by Microsoft Research India'
url:              'http://harsha-simhadri.org/'
baseurl:          /EdgeML

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         2

# Custom vars
github:
  repo:           https://github.com/harsha-simhadri/EdgeML

plugins:
  - jekyll-paginate
  - jekyll-gist

# For URL Setup, refer to
# https://github.com/jekyll/jekyll/issues/332#issuecomment-18952908